services:
  - type: web
    name: merchant-portal
    runtime: node
    region: singapore  # Changed to match your database region
    plan: starter   # Or 'free' for testing
    buildCommand: npm install && npm run build && npx prisma generate && npx prisma migrate deploy
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      # Database (auto-connected)
      - key: DATABASE_URL
        fromDatabase:
          name: portal-db
          property: connectionString
      
      # Security
      - key: JWT_SECRET
        generateValue: true
      
      # App Configuration
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3010
      - key: NEXTAUTH_URL
        sync: false  # Set manually after deployment
      
      # Salesforce (set in dashboard)
      - key: SF_USERNAME
        sync: false
      - key: SF_PASSWORD
        sync: false
      - key: SF_TOKEN
        sync: false
      - key: SF_LOGIN_URL
        value: https://test.salesforce.com
      
      # Lark (optional, set in dashboard)
      - key: LARK_APP_ID
        sync: false
      - key: LARK_APP_SECRET
        sync: false

databases:
  - name: portal-db
    plan: starter  # Or 'free' for testing
    databaseName: merchants
    user: merchantadmin