services:
  - type: web
    name: merchant-portal
    runtime: node
    region: oregon
    plan: starter
    buildCommand: npm install && npm run build && npx prisma generate && npx prisma migrate deploy
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: portal-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 3010
      - key: NEXTAUTH_URL
        value: https://merchant-portal.onrender.com

databases:
  - name: portal-db
    plan: starter
    databaseName: merchants